ignore_merge_commits = true

[changelog]
authors    = [{ username = "arunim-io", signature = "Mugdha Arunim Ahmed" }]
owner      = "arunim-io"
path       = "CHANGELOG.md"
repository = "apod-wallpaper"
